use datos
go
delete from fleteplanilla
delete from fletecarga
delete from visita
delete from pedipda
delete from nmaopera
delete from anmaopera
delete from ncabefac
delete from ncuerfac
delete from ncuervari
delete from afenpedido
delete from renmaope
delete from fleteren
delete from renflete
delete from idasociado
delete from CabePromo
delete from CuerPromo
delete from Maopera
delete from MovCtacte
delete from CabeCpra
delete from CabeFac
delete from CuerFac
delete from CuerVari
delete from CuerCpra
delete from TablaImp
delete from apagos
delete from MovCaja
delete from MovBcocar
delete from afestock
delete from AfeBcocar
delete from CuerOrd
delete from AfeCtacte
delete from CuerVariOrd
delete from TablaAsi
delete from MovStock
delete from AfeConcilia
delete from SaldoResBco
delete from AnMaopera
delete from CuerDeta
delete from CabeDeta
delete from CabeOrd
delete from existenc
delete from detanrocaja
delete from movpub
delete from cuerarqueo
delete from cbioprecio
delete from arqueo
delete from  cuervaricpra
delete from renafevdor
delete from rendivdor
delete from renvdormaope
delete from movvdorvale
